# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-20 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0003_auto_20180920_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
