# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-27 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0006_auto_20180922_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(blank=True, choices=[('b', 'Baby'), ('y', 'Young'), ('a', 'Adult'), ('s', 'Senior')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra large')], max_length=2),
        ),
    ]
