# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0007_auto_20180927_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('u', 'Unknown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dog',
            name='size',
            field=models.CharField(choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra large'), ('u', 'u')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userdog',
            name='status',
            field=models.CharField(choices=[('l', 'Liked'), ('d', 'Disliked'), ('u', 'Unkown')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='age',
            field=models.CharField(blank=True, choices=[('b', 'Baby'), ('y', 'Young'), ('a', 'Adult'), ('s', 'Senior')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='gender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userpref',
            name='size',
            field=models.CharField(blank=True, choices=[('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra large')], max_length=10),
        ),
    ]
