# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0008_auto_20180928_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age_group',
            field=models.CharField(default='b', max_length=10),
        ),
    ]
