# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-03 20:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0010_auto_20180929_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpref',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_pref', to=settings.AUTH_USER_MODEL),
        ),
    ]
