# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 18:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0012_auto_20181003_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_dog', to=settings.AUTH_USER_MODEL),
        ),
    ]
