# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-13 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pugorugh', '0016_auto_20181011_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age_group',
        ),
    ]
